### ISSUE TITLE
Bug with comment notification

### ISSUE THREAD

**Issue by gopenshaw** [Daviddt17/island-android-app#65]
During our demo we encountered a situation that might be a bug. There was a comment notification, and clicking on it said that there was no corresponding post. We don't think the post was deleted.

This may have happened when there were two comments on a post. User A had a post, user B made a comment, then user A made a comment. The notification on user B's device seemed to be broken.

Need to investigate and test this more...

**Comment by isdavid** [comment]
Fixed with PR #66
